### ISSUE TITLE
don't support node -V 8.0.0

### ISSUE THREAD

**Issue by zhuhongyan** [appium/appium-support#194]
**Warning:**

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new
![image](https://user-images.githubusercontent.com/20653605/86551991-42bf4200-bf79-11ea-95ee-ac15d162114b.png)

![image](https://user-images.githubusercontent.com/20653605/86552014-536fb800-bf79-11ea-87d8-71745f14c306.png)
don't support node -V 8.0.0

**Comment by KazuCocoa** [comment]
Yes, since we no longer support Node 8 since Appium 1.14.0
https://github.com/appium/appium/releases/tag/v1.14.0

**Comment by kaiqigong** [comment]
Hi,
I think it is better to update major version, otherwise, some old repo will fail on build with node8.
