### ISSUE TITLE
Race condition when creating /tmp directory when downloading APK files

### ISSUE THREAD

**Issue by alewang** [appium/appium-support#38]
On Line 20 of lib/tempdir.js of commit 78a53f1cd8570f1ce0ec0f6b38078c8553bccbcb (master branch as of posting this issue) in the tempDir() function, there is a race condition when creating a /tmp directory for downloading APK files because the async function is not `await`ed upon by the caller. The function is copied below for convenience:

```
async function tempDir () {
  let now = new Date();
  let filePath = nodePath.join(os.tmpDir(),
    [now.getFullYear(), now.getMonth(), now.getDate(),
    '-',
    process.pid,
    '-',
    (Math.random() * 0x100000000 + 1).toString(36)].join(''));
  // creates a temp directory using the date and a random string

  fs.mkdir(filePath);

  return filePath;
}
```

fs.mkdir refers to an async function from fs.js. However, the Promise returned from mkdir is not `await`ed upon, causing tempDir() to potentially return before the temporary directory is created. This function is indirectly called from appium-base-driver/lib/helpers.js's downloadFile function, called when an APK is downloaded: downloadFile() calls tempdir.js's path() function. path() then calls tempDir(). Although path() `await`s on tempDir(), the Promise returned by tempDir() is not the same Promise as returned from mkdir().

Effects of the race condition: In appium-base-driver's helpers.js module's downloadFile function, the function passed to the the bluebird 'B' Promise's constructor makes a call to _fs.createWriteStream. This function will throw an error because the temporary directory might not have created yet.

This issue report is connected with this Appium discussion thread: https://discuss.appium.io/t/appium-1-5-2-will-not-download-android-application-on-subsequent-sessions/9857

EDIT: Typo and clarifying bits of the "Effects of race condition" section

**Comment by alewang** [comment]
I've created a small PR for this: https://github.com/appium/appium-support/pull/39 :stuck_out_tongue:

**Comment by imurchie** [comment]
PR is merged an in the latest published version of `appium-support`. Thanks for figuring this out and fixing!
